# Generated by Django 4.0.5 on 2022-08-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('fb_url', models.URLField(max_length=255)),
                ('tw_url', models.URLField(max_length=255)),
                ('ins_url', models.URLField(max_length=255)),
            ],
        ),
    ]
