# Generated by Django 4.0.5 on 2022-08-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_online', '0002_alter_experts_fb_url_alter_experts_ins_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='experts',
            name='fb_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experts',
            name='ins_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experts',
            name='tw_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
