# Generated by Django 4.0.5 on 2022-08-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_online', '0003_experts_photo_alter_experts_fb_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='display_about_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experts',
            name='photo',
            field=models.ImageField(null=True, upload_to='expert_pics/'),
        ),
    ]
