# Generated by Django 4.0.5 on 2022-08-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_online', '0009_alter_course_total_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_student',
            field=models.IntegerField(choices=[(5, '5 Students'), (10, '10 Students'), (15, '15 Students'), (20, '20 Students'), (25, '25 Students'), (30, '30 Students')], max_length=11),
        ),
    ]
