# Generated by Django 4.0.5 on 2022-08-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_online', '0011_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
