# Generated by Django 4.0.5 on 2022-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_online', '0012_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
